# Generated by Django 4.2.23 on 2026-09-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("org_id", models.CharField(max_length=50)),
                ("location_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="SystemBEntry",
            fields=[
                (
                    "entry_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("record_ref", models.CharField(db_index=True, max_length=50)),
                ("recorded_on", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("import_error", models.TextField(blank=True, null=True)),
                (
                    "location_id",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comparison.location",
                    ),
                ),
            ],
            options={
                "db_table": "system_b_entries",
            },
        ),
        migrations.CreateModel(
            name="SystemARecord",
            fields=[
                (
                    "record_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("actor_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "base_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                (
                    "location_id",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comparison.location",
                    ),
                ),
            ],
            options={
                "db_table": "system_a_records",
            },
        ),
        migrations.CreateModel(
            name="Disagreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(db_index=True, max_length=50)),
                (
                    "disagreement_type",
                    models.CharField(
                        choices=[
                            ("MISSING_IN_B", "Record missing in System B"),
                            (
                                "ORPHAN_ENTRY",
                                "System B entry points to non-existent record",
                            ),
                            ("DUPLICATE_ENTRY", "Record has multiple System B entries"),
                            ("VALUE_MISMATCH", "Value mismatch between systems"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "system_a_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "system_b_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comparison.location",
                    ),
                ),
            ],
            options={
                "db_table": "disagreements",
                "indexes": [
                    models.Index(
                        fields=["disagreement_type"],
                        name="disagreemen_disagre_a63f8e_idx",
                    ),
                    models.Index(
                        fields=["system_a_value"], name="disagreemen_system__e7641a_idx"
                    ),
                    models.Index(
                        fields=["system_b_value"], name="disagreemen_system__920809_idx"
                    ),
                ],
            },
        ),
    ]
